name: "Analyze"

on:
  workflow_dispatch:
  push:
  
jobs:
  Analyze:
    runs-on: self-hosted
    permissions:
  # required for all workflows
      security-events: write

    steps:

    - uses: actions/checkout@v3
    - name: Checkout private actions
      uses: vweevers/multi-checkout-action@v1
      with:
        token: ${{ secrets.TOK }}
        repositories: |
          tonasodji/hello-world
          tonasodji/pvs-studio
      
        
    - name: Analyze
      run: |
        pvs-studio-analyzer trace -- make -j8
        pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
        plog-converter PVS-Studio.log -t sarif -o results.sarif
      
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
